export const naviMenu = [
    /*{
        icon:'home-o',
        title:'首页',
        to:'/'
    },*/{
        icon:'description',
        title:'风险配置',
        to:'/riskConfig'
    },{
        icon:'thumb-circle-o',
        title:'理财推荐',
        to:'/recommend'
    },{
        icon:'balance-list',
        title:'模拟投资',
        to:'/investSimulation'
    },{
        icon:'user',
        title:'模拟持仓',
        to:'/investSimulation/purchased'
    },{
        icon:'records-o',
        title:'交易记录',
        to:'/record'
    }
]